alias ls='ls --color=auto --group-directories-first'
alias lla='ls -FGlahp'
alias ll='ls -lGh'
alias la='ls -a'
alias lsi='feh -l'
alias view='feh -x -g 1280x720 -. '
alias cls='clear'
alias cd..='cd ..'
