#!/bin/bash

FIFO=~/.lemonbar.fifo

n="lemonbar-xft"
g="1600x25+0+0"
f1="FantasqueSansMono Nerd Font Mono:style=Regular:size=10"
f2="FantasqueSansMono Nerd Font Mono:style=Bold:size=10"
f3="FontAwesome:size=11"
BG="#c5b3a7"
FG="#f2f3f4"
PINK="#ec5ca1"
GREEN="#6df2a2"
WHITE="#ffffff"
BLACK="#484848"


clock() {
	while true; do
		echo "C%{T2}`date +%H:%M`%{T1}"
		sleep 1
	done
}

battery() {
	while true; do
		CAP=`cat /sys/class/power_supply/BAT0/capacity`
		case "$(cat /sys/class/power_supply/BAT0/status)" in
			D*)	STAT="" ;;
			*)	STAT="\uf0e7" ;;
		esac
		if (( 0 < CAP && CAP <= 20 )); then
			SYM="\uf244"
		elif (( 20 < CAP && CAP <= 40 )); then
			SYM="\uf243"
		elif (( 40 < CAP && CAP <= 60 )); then
			SYM="\uf242"
		elif (( 60 < CAP && CAP <= 80 )); then
			SYM="\uf241"
		else
			SYM="\uf240"
		fi
		echo "B%{T3}$STAT $SYM%{T1} $CAP%"
		sleep 5
	done
}

wifi() {
	while true; do
		SSID="`iw wlp3s0 info | grep -oP '(?<=ssid ).*$'`"
		if [ $SSID ]; then
			WIFI="\uf1eb"
		else
			WIFI="\uf141"
		fi
		echo "W%{T3}$WIFI%{T1O5} $SSID"
		sleep 5
	done
}

vpn() {
	while true; do
		case "`pvpn --status | grep -oP "(?<=OpenVPN Status]: ).*"`" in
			Not*)	VPN="\uf09c" ;;
			*)	VPN="%{F$GREEN}\uf023%{F-}" ;;
		esac
		echo "V%{T3}$VPN%{T1}"
		sleep 10
	done
}


trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -p "$FIFO" ] || mkfifo $FIFO

clock   > $FIFO &
battery > $FIFO &
wifi    > $FIFO &
vpn     > $FIFO &

while read -r line; do
	case $line in
		C*)	C="%{F$PINK}${line#?}%{O10}" ;;
		B*)	B="%{F$WHITE}${line#?}%{O10}" ;;
		W*)	W="%{F$WHITE}${line#?}%{O10}" ;;
		V*)	V="%{F$WHITE}${line#?}%{O10}" ;;
	esac
	echo -e "%{B$BLACK}%{O5%{l}$B%{c}$C%{r}$V$W%{O5}"
done < $FIFO | lemonbar -p -n $n -g $g -f "$f1" -f "$f2" -f "$f3" -B $BG -U $BLACK | sh &

wid=`xdo id -m -a $n`
xdo above -t `xdo id -N cwm -n root | sort | head -n 1` $wid


wait

